version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-dnd-html5-backend
    versions:
    - 11.1.3
    - 12.1.0
    - 12.1.1
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-dropzone
    versions:
    - 11.2.4
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: cross-env
    versions:
    - 7.0.2
